import archiver from "archiver";
import * as fs from "node:fs";
import { PassThrough } from "node:stream";

import type { VideoAsset } from "./pipeline/types";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface PageOutput {
  url: string;
  html: string;
  css: string;
  js: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function slugFromUrl(url: string): string {
  try {
    const parsed = new URL(url);
    const path = parsed.pathname.replace(/^\/+|\/+$/g, "");
    if (!path || path === "/") return "index";
    return path.replace(/\//g, "-").replace(/[^a-zA-Z0-9-_]/g, "");
  } catch {
    return "index";
  }
}

function buildReadme(pages: PageOutput[]): string {
  const pageList = pages
    .map((p, i) => `  ${i + 1}. ${slugFromUrl(p.url)}.html — ${p.url}`)
    .join("\n");

  return `OVERKILL TRANSFORMATION
========================

Your website has been transformed with premium effects.

Pages included:
${pageList}

HOW TO DEPLOY
-------------

Option 1: Static hosting (Vercel, Netlify, GitHub Pages)
  1. Upload the contents of this ZIP to your hosting provider.
  2. The entry point is index.html (or the first HTML file).

Option 2: Local preview
  1. Open any .html file directly in your browser.
  2. All dependencies are loaded from CDNs — no build step needed.

DEPENDENCIES (loaded from CDN)
------------------------------
- GSAP 3.12.5 (animations)
- GSAP ScrollTrigger (scroll-driven effects)
- Lenis 1.1.18 (smooth scrolling)

Generated by Overkill — https://overkill.dev
`;
}

// ---------------------------------------------------------------------------
// Package pages into a ZIP buffer
// ---------------------------------------------------------------------------

export async function packageTransformation(
  pages: PageOutput[],
  videoAsset?: VideoAsset,
): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const passthrough = new PassThrough();
    const chunks: Buffer[] = [];

    passthrough.on("data", (chunk: Buffer) => chunks.push(chunk));
    passthrough.on("end", () => resolve(Buffer.concat(chunks)));
    passthrough.on("error", reject);

    const archive = archiver("zip", { zlib: { level: 9 } });
    archive.on("error", reject);
    archive.pipe(passthrough);

    // Combine all CSS into one file
    const combinedCss = pages
      .map((p) => `/* Styles for ${p.url} */\n${p.css}`)
      .filter((s) => s.trim().length > 0)
      .join("\n\n");

    // Combine all JS into one file
    const combinedJs = pages
      .map((p) => `// Scripts for ${p.url}\n${p.js}`)
      .filter((s) => s.trim().length > 0)
      .join("\n\n");

    // Add HTML files
    const usedSlugs = new Set<string>();
    for (const page of pages) {
      let slug = slugFromUrl(page.url);

      // Deduplicate slugs
      if (usedSlugs.has(slug)) {
        let counter = 2;
        while (usedSlugs.has(`${slug}-${counter}`)) counter++;
        slug = `${slug}-${counter}`;
      }
      usedSlugs.add(slug);

      // Inject links to the shared CSS/JS files into the HTML
      const htmlWithAssets = injectAssetLinks(page.html);
      archive.append(htmlWithAssets, { name: `${slug}.html` });
    }

    // Add shared assets
    if (combinedCss.trim()) {
      archive.append(combinedCss, { name: "styles/overkill.css" });
    }
    if (combinedJs.trim()) {
      archive.append(combinedJs, { name: "scripts/overkill.js" });
    }

    // Add video asset if present
    if (videoAsset?.localPath && fs.existsSync(videoAsset.localPath)) {
      archive.file(videoAsset.localPath, { name: `assets/${videoAsset.filename}` });
    }

    // Add README
    archive.append(buildReadme(pages), { name: "README.txt" });

    archive.finalize();
  });
}

// ---------------------------------------------------------------------------
// Inject CSS/JS asset links into the HTML <head> and before </body>
// ---------------------------------------------------------------------------

function injectAssetLinks(html: string): string {
  let result = html;

  // Add CSS link in <head>
  const cssLink = '  <link rel="stylesheet" href="styles/overkill.css">\n';
  if (result.includes("</head>")) {
    result = result.replace("</head>", `${cssLink}</head>`);
  }

  // Add JS script before </body>
  const jsScript = '  <script src="scripts/overkill.js"></script>\n';
  if (result.includes("</body>")) {
    result = result.replace("</body>", `${jsScript}</body>`);
  }

  // Ensure CDN dependencies are present in <head>
  const cdnScripts = [
    "https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js",
    "https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js",
    "https://unpkg.com/lenis@1.1.18/dist/lenis.min.js",
  ];

  for (const src of cdnScripts) {
    if (!result.includes(src)) {
      const tag = `  <script src="${src}"></script>\n`;
      if (result.includes("</head>")) {
        result = result.replace("</head>", `${tag}</head>`);
      }
    }
  }

  return result;
}
